"""Phase 6 - assemble every cached result into the final tables.

Reads only `results/metrics/*.json` and writes `results/RESULTS.md`. It
computes nothing new: if a number is not already in a metrics file, it does not
appear. That is deliberate - a report generator that re-derives results is a
second implementation of the analysis, and two implementations disagree
eventually. Anything missing is reported as missing rather than filled in.

Handles any number of models, so Phase 6's second model slots in by being
extracted and probed; no edit here.

Usage
-----
    python scripts/06_report.py
    python scripts/06_report.py --models llama32-1b qwen25-1.5b
"""

from __future__ import annotations

import argparse
import json
import logging
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from src import paths  # noqa: E402
from src.logging_utils import setup_logging  # noqa: E402

MISSING = "n/a"

#: Canonical arm order. JSON keys come back alphabetically, which puts INT4
#: before INT8 and makes every table read as though precision decreases and
#: then increases. Ordering is part of the argument a table makes.
PRECISION_ORDER = ("fp16", "int8", "int4")


def ordered(arms) -> list[str]:
    """Arms in precision order, with anything unrecognised appended."""
    known = [p for p in PRECISION_ORDER if p in arms]
    return known + [a for a in arms if a not in PRECISION_ORDER]


def load(path: Path):
    if not path.is_file():
        return None
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError:
        return None


def discover_models(metrics_dir: Path) -> list[str]:
    """Every model with at least an E1 result."""
    return sorted(
        p.name[len("e1_per_layer_auroc_"):-len(".json")]
        for p in metrics_dir.glob("e1_per_layer_auroc_*.json")
    )


def fmt(value, spec: str = ".4f") -> str:
    return MISSING if value is None else format(value, spec)


def build(models: list[str], metrics_dir: Path, log) -> str:
    out: list[str] = []
    w = out.append

    w("# QuantProbe - results\n")
    w("Generated by `scripts/06_report.py` from `results/metrics/*.json`.")
    w("Every number below is read from a cached metrics file; nothing is")
    w("recomputed here, and anything absent is shown as " + MISSING + ".\n")

    # ------------------------------------------------------------ headline
    w("## Headline\n")
    w("| model | arm | probe AUROC (E1) | best layer | task acc (E5) | abstention AUC |")
    w("|---|---|---|---|---|---|")
    for model in models:
        e1 = load(metrics_dir / f"e1_per_layer_auroc_{model}.json")
        e5 = load(metrics_dir / f"e5_behavioural_{model}.json")
        ab = load(metrics_dir / f"abstention_{model}.json")
        arms = ordered(e1["best_layer"]) if e1 else []
        for arm in arms:
            best = e1["best_layer"][arm]
            task = None
            if e5 and arm in e5.get("results", {}):
                task = e5["results"][arm].get("halueval_qa", {}).get("accuracy")
            abst = None
            if ab and arm in ab.get("results", {}):
                abst = ab["results"][arm].get("auc_coverage_risk")
            w(f"| {model} | {arm.upper()} | {fmt(best['auroc_mean'])} "
              f"± {fmt(best['auroc_std'], '.3f')} | {best['layer']} | "
              f"{fmt(task)} | {fmt(abst)} |")
    w("")

    # ----------------------------------------------------------------- E1
    w("## E1 - per-layer probe AUROC\n")
    for model in models:
        e1 = load(metrics_dir / f"e1_per_layer_auroc_{model}.json")
        if not e1:
            w(f"### {model}\n\n{MISSING} no E1 results\n")
            continue
        arms = ordered(e1["best_layer"])
        rows = [r for r in e1["results"] if r["probe_type"] == "logistic"]
        layers = sorted({r["layer"] for r in rows})
        w(f"### {model}")
        w(f"\n{e1['n_fits']} fits - {len(e1['folds'])} folds "
          f"({', '.join(e1['folds'])}) - split `{e1['split_scheme']}`")
        if e1.get("leakage_flags"):
            w(f"\n**Leakage warnings:** {len(e1['leakage_flags'])}\n")
        w("")
        w("| layer | " + " | ".join(a.upper() for a in arms) + " |")
        w("|---" * (len(arms) + 1) + "|")
        for layer in layers:
            cells = []
            for arm in arms:
                m = [r for r in rows if r["precision"] == arm and r["layer"] == layer]
                cells.append(f"{m[0]['auroc_mean']:.4f}" if m else MISSING)
            w(f"| {layer} | " + " | ".join(cells) + " |")
        w("")

    # ----------------------------------------------------------------- E2
    w("## E2 - cross-precision transfer\n")
    for model in models:
        e = load(metrics_dir / f"e2_e3_e4_{model}.json")
        if not e:
            w(f"### {model}\n\n{MISSING} no Phase 4 results\n")
            continue
        arms = ordered(e["precisions"])
        w(f"### {model} - layer {e['peak_layer']} (strongest matched)\n")
        w("AUROC, rows = trained on, cols = tested on:\n")
        w("| trained on | " + " | ".join(a.upper() for a in arms) + " |")
        w("|---" * (len(arms) + 1) + "|")
        # The stored matrix is indexed by the ORIGINAL order in the json, so
        # the rows and columns must be permuted together with the labels -
        # relabelling alone would silently transpose the meaning of cells.
        src = e["precisions"]
        perm = [src.index(a) for a in arms]
        for a, i in zip(arms, perm):
            w(f"| **{a.upper()}** | "
              + " | ".join(f"{e['e2_matrix_at_peak'][i][j]:.4f}" for j in perm) + " |")
        w("")
        w("Mean loss vs the native probe, averaged over all layers:\n")
        w("| trained on | tested on | loss |")
        w("|---|---|---|")
        for a in arms:
            for b in arms:
                if a == b:
                    continue
                vals = [r["loss"] for r in e["e2_loss"]
                        if r["train_precision"] == a and r["test_precision"] == b]
                if vals:
                    w(f"| {a.upper()} | {b.upper()} | {sum(vals)/len(vals):+.4f} |")
        w("")

    # -------------------------------------------------------------- E3/E4
    w("## E3 / E4 - drift and probe rotation\n")
    for model in models:
        e = load(metrics_dir / f"e2_e3_e4_{model}.json")
        if not e:
            w(f"### {model}\n\n{MISSING} no Phase 4 results\n")
            continue
        w(f"### {model}\n")
        w("| layer | rel drift INT4 | cosine INT4 | CKA INT4 | "
          "probe angle INT4 | FP16 noise floor | excess |")
        w("|---|---|---|---|---|---|---|")
        drift = {r["layer"]: r for r in e["e3_drift"] if r["precision"] == "int4"}
        rot = {r["layer"]: r for r in e["e4_rotation"] if r["precision"] == "int4"}
        for layer in sorted(drift):
            d, r = drift[layer], rot.get(layer)
            w(f"| {layer} | {d['relative_drift']:.4f} | {d['mean_cosine']:.5f} | "
              f"{d['linear_cka']:.5f} | "
              + (f"{r['angle_deg']:.1f}° | {r['baseline_deg']:.1f}° | "
                 f"{r['excess_deg']:+.1f}° |" if r else f"{MISSING} | {MISSING} | {MISSING} |"))
        w("")
        w("**H4 (restated) - drift vs transfer loss:**\n")
        w("| comparison | Pearson r | p | Spearman rho | p |")
        w("|---|---|---|---|---|")
        for key, c in e.get("h4_restated_correlations", {}).items():
            if c.get("pearson_r") is None:
                w(f"| `{key}` | {MISSING} | | | |")
            else:
                w(f"| `{key}` | {c['pearson_r']:+.3f} | {c['pearson_p']:.3f} | "
                  f"{c['spearman_rho']:+.3f} | {c['spearman_p']:.3f} |")
        w("")

    # ----------------------------------------------------------------- E5
    w("## E5 - behavioural control\n")
    for model in models:
        e5 = load(metrics_dir / f"e5_behavioural_{model}.json")
        if not e5:
            w(f"### {model}\n\n{MISSING} no E5 results\n")
            continue
        w(f"### {model}\n")
        w("| arm | HaluEval acc | 95% CI | MC1 acc (sum) | MC1 acc (mean) |")
        w("|---|---|---|---|---|")
        for arm in ordered(e5["results"]):
            r = e5["results"][arm]
            h = r.get("halueval_qa", {})
            m = r.get("truthfulqa_mc1", {})
            ci = h.get("accuracy_ci")
            w(f"| {arm.upper()} | {fmt(h.get('accuracy'))} | "
              f"{'[%.4f, %.4f]' % tuple(ci) if ci else MISSING} | "
              f"{fmt(m.get('accuracy_logprob_sum'))} | "
              f"{fmt(m.get('accuracy_logprob_mean'))} |")
        lc = e5.get("mc1_length_confound")
        if lc:
            w("")
            w(f"**MC1 length confound:** always-shortest "
              f"{lc['accuracy_if_always_shortest']:.4f}, always-longest "
              f"{lc['accuracy_if_always_longest']:.4f}. {lc.get('verdict', '')}")
        w("")

    # ---------------------------------------------------------- abstention
    w("## Probe-guided abstention\n")
    for model in models:
        ab = load(metrics_dir / f"abstention_{model}.json")
        if not ab:
            w(f"### {model}\n\n{MISSING} no abstention results\n")
            continue
        w(f"### {model} - layer {ab['layer']}\n")
        first = next(iter(ab["results"].values()))
        w(f"Base false-assertion rate with no filter: "
          f"**{first['baseline_false_rate']*100:.1f}%**\n")
        w("| arm | answer 90% | answer 71% | answer 48% | AUC (lower better) |")
        w("|---|---|---|---|---|")
        for arm in ordered(ab["results"]):
            r = ab["results"][arm]
            ops = r["operating_points"]
            w(f"| {arm.upper()} | "
              + " | ".join(f"{ops[k]['false_assertion_rate']*100:.1f}%"
                           for k in ("coverage_90", "coverage_70", "coverage_50"))
              + f" | {r['auc_coverage_risk']:.4f} |")
        w("")

    # -------------------------------------------------------------- figures
    figures = sorted(paths.figures_dir().glob("*.png"))
    if figures:
        w("## Figures\n")
        for f in figures:
            w(f"- `results/figures/{f.name}`")
        w("")

    return "\n".join(out)


def main() -> int:
    args = parse_args()
    log = setup_logging(log_dir=paths.logs_dir(), level=logging.INFO)
    metrics_dir = paths.metrics_dir()

    models = args.models or discover_models(metrics_dir)
    if not models:
        log.error("no models found in %s - run scripts/02_probe.py first", metrics_dir)
        return 1
    log.info("assembling results for: %s", models)

    text = build(models, metrics_dir, log)
    out = paths.results_dir() / "RESULTS.md"
    out.write_text(text, encoding="utf-8")

    # Count table cells only. An earlier version counted every occurrence of
    # the marker character, including legitimate ones in headings, and
    # reported 12 gaps in a report that had none.
    missing = text.count("| " + MISSING)
    log.info("wrote %s (%d lines, %d missing entries)",
             out, len(text.splitlines()), missing)
    if missing:
        log.warning("%d entries are missing - those experiments have not been run "
                    "for every model yet", missing)
    return 0


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="QuantProbe - final results tables")
    parser.add_argument("--models", nargs="*", default=None,
                        help="default: every model with an E1 result")
    return parser.parse_args()


if __name__ == "__main__":
    sys.exit(main())
